### PR TITLE
rebase to ubuntu vanilla, using .net core builds of jackett

### LINKED ISSUE #74: with 5.14 mono, jackett fails to connect to torrent sites
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

using :latest pull of jackett. 

```
docker inspect -f '{{ index .Config.Labels "build_version" }}' jackett
Linuxserver.io version:- v0.10.903-ls11 Build-date:- 2019-03-06T10:07:14+00:00
```
```
docker inspect -f '{{ index .Config.Labels "build_version" }}' linuxserver/jackett
Linuxserver.io version:- v0.10.903-ls11 Build-date:- 2019-03-06T10:07:14+00:00
```

```
# mono -V
Mono JIT compiler version 5.14.0.177 (tarball Mon Aug  6 09:13:43 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)
```

docker version and host information: 
```
docker info
Containers: 28
 Running: 28
 Paused: 0
 Stopped: 0
Images: 26
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.18-11-pve
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.86GiB
Name: proxmox
ID: FZSK:WGVO:N675:IX5T:TSXA:MVTA:HFZR:TKQ6:XU2Z:X7IH:5MBZ:PF2Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

```
uname -a
Linux proxmox 4.15.18-11-pve #1 SMP PVE 4.15.18-34 (Mon, 25 Feb 2019 14:51:06 +0100) x86_64 GNU/Linux
```

host is proxmox (debian) latest community version.

after an unknown period of time , all of my torrent sites fail with the following message in the webui. 

Screenshot 2019-03-09 at 15 43 08

the log is full of bajillions of stacktrace messages, sample below...

```
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <0906f7e0790f445ba4d1e9d6fcb7f88d>:0
```

restarting the container "fixes" the issue, but so far it has reverted to being broken again 3 times in the last 2 days.

### PR DESCRIPTION
**Pull request by sparklyballs**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

+ closes #74 
+ not sure if anything needs changing in Jenkinsfile or jenkins var files.

### CODE REVIEW

**Comment by sparklyballs** [comment]
well that makes no sense because i built everything locally and span them up with no probs. 

aarch64 

Screenshot 2019-03-10 at 11 52 28

armhf 

Screenshot 2019-03-10 at 11 53 13

x86-64

Screenshot 2019-03-10 at 11 54 41

**Comment by sparklyballs** [comment]
nvm, missed the qemu stuff on armxx Dockerfiles.

**Comment by sparklyballs** [comment]
i've been using the preview-dev branch ,i.e. netcore, that @thelamer suggested in the issue i raised last night. 

i can't find anything wrong and it's a drop-in replacement with existing data from the mono version.

**Comment by sparklyballs** [comment]
@thelamer 

this will get the latest tag, but it doesn't differentiate between release and pre-release, it gets the latest tag regardless. 
```
JACKETT_RELEASE=$(curl -sX GET "https://api.github.com/repos/Jackett/Jackett/tags" \
| jq -r .[0].name)
```

while it will fetch pre-releases, that the master branch will not, if the latest tag is a release, then the dev branch and the master branch will be the same tag.

**Comment by thelamer** [comment]
you can use: 

```
JACKETT_RELEASE=$(curl -sX GET "https://api.github.com/repos/Jackett/Jackett/releases" \
| jq -r 'first(.[] | select(.prerelease == true)) | .tag_name')
```
But I think @aptalca wants to ingest the first in the array ` jq -r '.[0]'` as their stable releases can technically be ahead of their pre releases at times. 

Sorry when I said tag I was referring to the releases endpoint tag_name, not literal tags. That endpoint is fucked, they do not sort it by date so you cannot trust it's output order.

**Pull request merged**
