### PR TITLE
Add env var to allow pre-build version of Jackett installation

### LINKED ISSUE #30: Allow to install pre-build version of Jackett
Is it possible to let us install pre-build version of Jackett to get lastest trackers?

Thanks

### PR DESCRIPTION
**Pull request by welcoMattic**
Fixes #30

### CODE REVIEW

**Comment by sparklyballs** [comment]
just no

**Comment by sparklyballs** [comment]
building different version by ENV var etc just begs the question as to why you don't just change the line in the git lookup and build locally

**Comment by welcoMattic** [comment]
Because I'm using it in a docker-compose stack. It should be an option to allow user of this image to install a pre-build version of Jackett.
I'm not changing the default, I'm adding an option.
With this possibility, everyone can choose, and pre-build version allows us to have latest trackers list on Jackett.

Please don't close savagely PR without any discussion, it's not respectful.

**Comment by sparklyballs** [comment]
which you still have to build locally. 

hence why not just change the Dockerfile locally and build locally rather than force a change on the whole repo to suit your personal environment.

**Comment by welcoMattic** [comment]
I thought about that, but as docker-jackett is open source, I prefer to submit with a PR to share it. But, obviously you really don't want any change here, so let me do this for my personal use. 

I just want to precise that my changes don't affect any default behaviour of the image, it's just adding an option. It's not BC break. It's not a total rewriting of the Dockerfile.

**Comment by sparklyballs** [comment]
open source does not mean accept all PR's

**Comment by welcoMattic** [comment]
Of course, it doesn't mean accept all PR's, but generally PR adding not useless options are accepted, or discussed. Not first closed.

Enough for me, I'll use my fork.

**Comment by CHBMB** [comment]
Whilst I accept the PR is not a bad idea per se, it does mean it's added complexity that we have to support, so we tend to favour keeping things simple.   Not everyone is a technically minded as yourself @welcoMattic we have a lot less tech savvy users from different platforms you see.

**Pull request closed without merging**
